spring.application.name=paas

spring.datasource.url=jdbc:postgresql://localhost:5432/paas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml